default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5

development:
  <<: *default
  database: FictionCapital_development

test:
  <<: *default
  database: FictionCapital_test

production:
  <<: *default
  database: FictionCapital_production
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>