# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b016c84097f2fd837f7be230c63780e4b31f7bf26d4dee5b6c0e6346dbeba83a70d1ed8288cef701205b3ce6fe0604856a44e82376427a5d284fd09ca7881c4

test:
  secret_key_base: 4da84dbf5fb8202bc96588860dfb9833fb6fad8f87315789ea17985553ef26b9fbad69b9b401a10268d1e82da440eef923d583d3b0661f0e94a24cd026e52aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
